<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="Silk.NET" Version="2.18.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.18.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.18.0" />
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
    <PackageReference Include="SoLoud" Version="1.0.0" />
    <PackageReference Include="SharpGLTF" Version="1.0.0" />
  </ItemGroup>

</Project>
