<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenEngine.Core\OpenEngine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET" Version="2.21.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.21.0" />
    <PackageReference Include="ImGui.NET" Version="1.90.1.1" />
    <PackageReference Include="ImGui.NET.Silk.NET" Version="1.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
